spring:
  application:
    name: translator

  boot:
    repackage:
      exclude: com.github.kwhat:jnativehook

translator:
  google:
    enabled: true
    url: https://translate.google.com
    api:
      translate: /translate_a/single?client=at&dt=t&dj=1

logging:
  level:
    org.jnativehook.GlobalScreen: ERROR
